// <auto-generated />
using H3WebshopProeveprojekt.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace H3WebshopProeveprojekt.Api.Migrations
{
    [DbContext(typeof(H3WebshopProeveprojektContext))]
    [Migration("20220322070741_added-productImage")]
    partial class addedproductImage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("H3WebshopProeveprojekt.Api.Database.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountRoleId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserFirstName")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserLastName")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("AccountRoleId");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("H3WebshopProeveprojekt.Api.Database.Entities.AccountRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("AccountRole");
                });

            modelBuilder.Entity("H3WebshopProeveprojekt.Api.Database.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Trousers"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Shirts"
                        });
                });

            modelBuilder.Entity("H3WebshopProeveprojekt.Api.Database.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<byte>("DiscountPercentage")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(30)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductImage")
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DiscountPercentage = (byte)0,
                            Name = "Jeans",
                            Price = 400.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            DiscountPercentage = (byte)0,
                            Name = "Woolies",
                            Price = 300.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            DiscountPercentage = (byte)0,
                            Name = "Serena shirt",
                            Price = 600.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            DiscountPercentage = (byte)0,
                            Name = "Tshirt",
                            Price = 200.0
                        });
                });

            modelBuilder.Entity("H3WebshopProeveprojekt.Api.Database.Entities.Account", b =>
                {
                    b.HasOne("H3WebshopProeveprojekt.Api.Database.Entities.AccountRole", "AccountRole")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountRole");
                });

            modelBuilder.Entity("H3WebshopProeveprojekt.Api.Database.Entities.Product", b =>
                {
                    b.HasOne("H3WebshopProeveprojekt.Api.Database.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("H3WebshopProeveprojekt.Api.Database.Entities.AccountRole", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("H3WebshopProeveprojekt.Api.Database.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
